local s = require("themes.selenized.scheme")

return {
  -- Core editor UI
  Normal = { fg = s.fg_0, bg = s.bg_0 },
  NormalFloat = { link = "Normal" },
  NormalNC = { link = "Normal" },
  Cursor = { reverse = true },
  CursorLine = { bg = s.bg_1 },
  CursorColumn = { link = "CursorLine" },
  CursorLineNr = { fg = s.fg_1 },

  ColorColumn = { bg = s.bg_2 },
  Directory = { fg = s.blue },
  EndOfBuffer = { fg = s.bg_0 },
  ErrorMsg = { fg = s.red },
  FloatBorder = { fg = s.dim_0 },
  FloatTitle = {},
  FoldColumn = {},
  Folded = {},
  IncSearch = {},
  LineNr = {},
  MatchParen = {},
  ModeMsg = {},
  MoreMsg = {},
  NonText = {},

  -- Popup menu
  Pmenu = {},
  PmenuSbar = {},
  PmenuSel = {},
  PmenuThumb = {},

  -- Spelling
  SpellBad = {},
  SpellCap = {},
  SpellLocal = {},
  SpellRare = {},

  -- Status line highlights
  StatusLineNormal = {},
  StatusLineInsert = {},
  StatusLineVisual = {},
  StatusLineCommand = {},
  StatusLineReplace = {},
  StatusLineTerminal = {},
  StatusLineFile = {},
  StatusLineModified = {},
  StatusLineReadonly = {},
  StatusLineGit = {},
  StatusLineInfo = {},
  StatusLineLabel = {},
  StatusLineValue = {},
  StatusLineDiagError = {},
  StatusLineDiagWarn = {},
  StatusLineDiagInfo = {},
  StatusLineDiagHint = {},
  StatusLineLSP = {},
  StatusLine = {},
  StatusLineNC = {},

  -- Search and selection
  Question = {},
  QuickFixLine = {},
  Search = {},
  SignColumn = {},
  SpecialKey = {},

  -- Tabs
  TabLine = {},
  TabLineFill = {},
  TabLineSel = {},

  -- Miscellaneous
  Title = {},
  VertSplit = {},
  Visual = {},
  VisualNOS = {},
  WarningMsg = {},
  Whitespace = {},
  WildMenu = {},
  WinSeparator = {},

  -- LSP Reference highlighting
  LspReferenceRead = {},
  LspReferenceWrite = {},
  LspReferenceText = {},

  -- LSP Signature help
  LspSignatureActiveParameter = {},

  -- LSP Code lens
  LspCodeLens = {},
  LspCodeLensSeparator = {},

  -- Diagnostic highlights
  DiagnosticError = {},
  DiagnosticWarn = {},
  DiagnosticInfo = {},
  DiagnosticHint = {},
  DiagnosticOk = {},
  DiagnosticUnderlineError = {},
  DiagnosticUnderlineWarn = {},
  DiagnosticUnderlineInfo = {},
  DiagnosticUnderlineHint = {},
  DiagnosticUnderlineOk = {},
  DiagnosticVirtualTextError = {},
  DiagnosticVirtualTextWarn = {},
  DiagnosticVirtualTextInfo = {},
  DiagnosticVirtualTextHint = {},
  DiagnosticVirtualTextOk = {},
  DiagnosticFloatingError = {},
  DiagnosticFloatingWarn = {},
  DiagnosticFloatingInfo = {},
  DiagnosticFloatingHint = {},
  DiagnosticFloatingOk = {},
  DiagnosticSignError = {},
  DiagnosticSignWarn = {},
  DiagnosticSignInfo = {},
  DiagnosticSignHint = {},
  DiagnosticSignOk = {},

  DiffAdd = {},
  DiffChange = {},
  DiffDelete = {},
  DiffText = {},
  GitSignsAdd = {},
  GitSignsChange = {},
  GitSignsDelete = {},

  Terminal0 = {},
  Terminal1 = {},
  Terminal2 = {},
  Terminal3 = {},
  Terminal4 = {},
  Terminal5 = {},
  Terminal6 = {},
  Terminal7 = {},
  Terminal8 = {},
  Terminal9 = {},
  Terminal10 = {},
  Terminal11 = {},
  Terminal12 = {},
  Terminal13 = {},
  Terminal14 = {},
  Terminal15 = {},
}
