local p = require("themes.selenized.scheme")

return {
  -- Blink.cmp (completion plugin)
  BlinkCmpMenuBorder = {},
  BlinkCmpLabelMatch = {},
  BlinkCmpLabelDescription = {},
  BlinkCmpLabelDetail = {},
  BlinkCmpKind = {},
  BlinkCmpKindText = {},
  BlinkCmpKindMethod = {},
  BlinkCmpKindFunction = {},
  BlinkCmpKindConstructor = {},
  BlinkCmpKindField = {},
  BlinkCmpKindVariable = {},
  BlinkCmpKindClass = {},
  BlinkCmpKindInterface = {},
  BlinkCmpKindModule = {},
  BlinkCmpKindProperty = {},
  BlinkCmpKindUnit = {},
  BlinkCmpKindValue = {},
  BlinkCmpKindEnum = {},
  BlinkCmpKindKeyword = {},
  BlinkCmpKindSnippet = {},
  BlinkCmpKindColor = {},
  BlinkCmpKindFile = {},
  BlinkCmpKindReference = {},
  BlinkCmpKindFolder = {},
  BlinkCmpKindEnumMember = {},
  BlinkCmpKindConstant = {},
  BlinkCmpKindStruct = {},
  BlinkCmpKindEvent = {},
  BlinkCmpKindOperator = {},
  BlinkCmpKindTypeParameter = {},

  -- Neo-tree (file explorer)
  NeoTreeBufferNumber = {},
  NeoTreeCursorLine = {},
  NeoTreeDimText = {},
  NeoTreeDirectoryIcon = {},
  NeoTreeDirectoryName = {},
  NeoTreeDotfile = {},
  NeoTreeFileIcon = {},
  NeoTreeFileName = {},
  NeoTreeFileNameOpened = {},
  NeoTreeFilterTerm = {},
  NeoTreeFloatBorder = {},
  NeoTreeFloatTitle = {},
  NeoTreeTitleBar = {},

  -- Neo-tree Git integration
  NeoTreeGitAdded = {},
  NeoTreeGitConflict = {},
  NeoTreeGitDeleted = {},
  NeoTreeGitIgnored = {},
  NeoTreeGitModified = {},
  NeoTreeGitUnstaged = {},
  NeoTreeGitUntracked = {},
  NeoTreeGitStaged = {},

  -- Neo-tree UI elements
  NeoTreeHiddenByName = {},
  NeoTreeIndentMarker = {},
  NeoTreeExpander = {},
  NeoTreeNormal = {},
  NeoTreeNormalNC = {},
  NeoTreeSignColumn = {},
  NeoTreeStats = {},
  NeoTreeStatsHeader = {},
  NeoTreeStatusLine = {},
  NeoTreeStatusLineNC = {},
  NeoTreeVertSplit = {},
  NeoTreeWinSeparator = {},
  NeoTreeRootName = {},
  NeoTreeSymbolicLinkTarget = {},
  NeoTreeWindowsHidden = {}
}
