local M = {}

M.get = function(c)
  return {
    Bold = { bold = true, fg = c.fg },
    Character = { fg = c.green },
    ColorColumn = { bg = c.black },
    Comment = { fg = c.comment, italic = true },
    Conceal = { fg = c.dark5 },
    Constant = { fg = c.orange },
    CurSearch = { link = "IncSearch" },
    Cursor = { fg = c.bg, bg = c.fg },
    CursorColumn = { link = "CursorLine" },
    CursorIM = { fg = c.bg, bg = c.fg },
    CursorLine = { bg = c.bg_dark2 },
    CursorLineNr = { fg = c.orange, bold = true },
    Debug = { link = "Constant" },
    Delimiter = { link = "Special" },
    DiagnosticError = { fg = c.red },
    DiagnosticHint = { fg = c.teal },
    DiagnosticInfo = { fg = c.blue2 },
    DiagnosticUnderlineError = { undercurl = true, sp = c.red },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.teal },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue2 },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
    DiagnosticUnnecessary = { fg = c.bg_dark3 },
    DiagnosticVirtualTextError = { bg = c.error_bg, fg = c.red },
    DiagnosticVirtualTextHint = { bg = c.hint_bg, fg = c.teal },
    DiagnosticVirtualTextInfo = { bg = c.info_bg, fg = c.blue2 },
    DiagnosticVirtualTextWarn = { bg = c.warn_bg, fg = c.yellow },
    DiagnosticWarn = { fg = c.yellow },
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { bg = c.blue7 },
    Directory = { fg = c.blue },
    EndOfBuffer = { fg = c.bg },
    Error = { fg = c.red },
    ErrorMsg = { fg = c.red },
    FloatBorder = { fg = c.border_highlight, bg = c.bg_dark },
    FloatTitle = { link = "FloatBorder" },
    FoldColumn = { bg = c.background, fg = c.comment },
    Folded = { fg = c.blue, bg = c.fg_gutter },
    Function = { fg = c.blue, bold = true, nocombine = true },
    Identifier = { fg = c.magenta },
    IncSearch = { bg = c.orange, fg = c.black },
    Italic = { italic = true, fg = c.fg },
    Keyword = { fg = c.magenta },
    LineNr = { fg = c.fg_gutter, bg = c.background },
    LineNrAbove = { fg = c.fg_gutter },
    LineNrBelow = { fg = c.fg_gutter },
    LspCodeLens = { fg = c.comment },
    LspInfoBorder = { fg = c.border_highlight, bg = c.bg_dark },
    LspInlayHint = { bg = c.lsp_inlay_hint, fg = c.dark3 },
    LspReferenceRead = { bg = c.fg_gutter },
    LspReferenceText = { bg = c.fg_gutter },
    LspReferenceWrite = { bg = c.fg_gutter },
    LspSignatureActiveParameter = { bg = c.lsp_signature_active_param, bold = true },
    MatchParen = { fg = c.orange, bold = true },
    ModeMsg = { fg = c.fg_dark, bold = true },
    MoreMsg = { fg = c.blue },
    MsgArea = { fg = c.fg_dark },
    NonText = { fg = c.fg_gutter, nocombine = true },
    Normal = { fg = c.fg, bg = c.background },
    NormalFloat = { fg = c.fg, bg = c.bg_dark },
    NormalNC = { fg = c.fg, bg = c.background },
    NormalSB = { fg = c.fg_dark, bg = c.bg_dark },
    Operator = { fg = c.blue5 },
    Pmenu = { bg = c.bg_dark, fg = c.fg },
    PmenuMatch = { bg = c.bg_dark, fg = c.blue1 },
    PmenuMatchSel = { bg = c.match_sel, fg = c.blue1 },
    PmenuSbar = { bg = c.s_bar },
    PmenuSel = { bg = c.menu_sel },
    PmenuThumb = { bg = c.fg_gutter },
    PreProc = { fg = c.cyan },
    Question = { fg = c.blue },
    QuickFixLine = { bg = c.bg_visual, bold = true },
    Search = { bg = c.blue0, fg = c.fg },
    SignColumn = { bg = c.background, fg = c.fg_gutter },
    SignColumnSB = { bg = c.bg_dark, fg = c.fg_gutter },
    Special = { fg = c.blue1, nocombine = true },
    SpecialKey = { fg = c.dark3 },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellLocal = { sp = c.blue2, undercurl = true },
    SpellRare = { sp = c.teal, undercurl = true },
    Statement = { link = "Keyword" },
    StatusLine = { fg = c.fg_dark, bg = c.dark },
    StatusLineNC = { fg = c.fg_gutter, bg = c.dark },
    String = { link = "Character" },
    Substitute = { bg = c.red, fg = c.black },
    TabLine = { bg = c.dark, fg = c.fg_gutter },
    TabLineFill = { bg = c.black },
    TabLineSel = { fg = c.black, bg = c.blue },
    Title = { fg = c.blue, bold = true },
    Todo = { bg = c.yellow, fg = c.bg },
    Type = { fg = c.type_var },
    Underlined = { underline = true },
    Visual = { bg = c.bg_visual },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = c.yellow },
    Whitespace = { fg = c.fg_gutter, nocombine = true },
    WildMenu = { link = "Visual" },
    WinBar = { link = "StatusLine" },
    WinBarNC = { link = "StatusLineNC" },
    WinSeparator = { fg = c.fg_gutter },
    lCursor = { link = "Cursor" },
  }
end

return M
