local M = {}

M.get = function(c)
  return {
    -- UI Elements
    ColorColumn = { bg = c.black },
    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = { fg = c.bg, bg = c.fg },
    CursorIM = { fg = c.bg, bg = c.fg },
    CursorLine = { bg = c.bg_dark2 },
    CursorColumn = { link = "CursorLine" },
    CursorLineNr = { fg = c.orange, bold = true },
    EndOfBuffer = { fg = c.bg },
    LineNr = { fg = c.fg_gutter },
    LineNrAbove = { fg = c.fg_gutter },
    LineNrBelow = { fg = c.fg_gutter },
    Normal = { fg = c.fg, bg = c.background },
    NormalNC = { fg = c.fg, bg = c.background },
    NormalSB = { fg = c.fg_dark, bg = c.bg_dark },
    NormalFloat = { fg = c.fg, bg = c.bg_dark },
    FloatBorder = { fg = c.border_highlight, bg = c.bg_dark },
    FloatTitle = { link = "FloatBorder" },
    StatusLine = { fg = c.fg_dark, bg = c.dark },
    StatusLineNC = { fg = c.fg_gutter, bg = c.dark },
    WinBar = { link = "StatusLine" },
    WinBarNC = { link = "StatusLineNC" },
    WinSeparator = { fg = c.fg_gutter },
    TabLine = { bg = c.dark, fg = c.fg_gutter },
    TabLineFill = { bg = c.black },
    TabLineSel = { fg = c.black, bg = c.blue },
    SignColumn = { bg = c.background, fg = c.fg_gutter },
    SignColumnSB = { bg = c.bg_dark, fg = c.fg_gutter },
    FoldColumn = { bg = c.background, fg = c.comment },
    QuickFixLine = { bg = c.bg_visual, bold = true },
    -- Syntax Highlighting
    Comment = { fg = c.comment, italic = true },
    Character = { fg = c.green },
    Constant = { fg = c.orange },
    String = { link = "Character" },
    Identifier = { fg = c.magenta },
    Function = { fg = c.blue, bold = true, nocombine = true },
    Keyword = { fg = c.magenta },
    Operator = { fg = c.blue5 },
    PreProc = { fg = c.cyan },
    Statement = { link = "Keyword" },
    Type = { fg = c.type_var },
    Special = { fg = c.blue1, nocombine = true },
    Delimiter = { link = "Special" },
    Debug = { link = "Constant" },
    -- Diff and Version Control
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { bg = c.blue7 },
    -- Diagnostics
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.yellow },
    DiagnosticInfo = { fg = c.blue2 },
    DiagnosticHint = { fg = c.teal },
    DiagnosticUnnecessary = { fg = c.bg_dark3 },
    DiagnosticVirtualTextError = { bg = c.error_bg, fg = c.red },
    DiagnosticVirtualTextWarn = { bg = c.warn_bg, fg = c.yellow },
    DiagnosticVirtualTextInfo = { bg = c.info_bg, fg = c.blue2 },
    DiagnosticVirtualTextHint = { bg = c.hint_bg, fg = c.teal },
    DiagnosticUnderlineError = { undercurl = true, sp = c.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.blue2 },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.teal },
    -- Popup Menu
    Pmenu = { bg = c.bg_dark, fg = c.fg },
    PmenuMatch = { bg = c.bg_dark, fg = c.blue1 },
    PmenuSel = { bg = c.menu_sel },
    PmenuMatchSel = { bg = c.match_sel, fg = c.blue1 },
    PmenuSbar = { bg = c.s_bar },
    PmenuThumb = { bg = c.fg_gutter },
    -- Search and Highlights
    Search = { bg = c.blue0, fg = c.fg },
    IncSearch = { bg = c.orange, fg = c.black },
    CurSearch = { link = "IncSearch" },
    MatchParen = { fg = c.orange, bold = true },
    Visual = { bg = c.bg_visual },
    VisualNOS = { link = "Visual" },
    WildMenu = { link = "Visual" },
    -- Spelling
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.yellow, undercurl = true },
    SpellLocal = { sp = c.blue2, undercurl = true },
    SpellRare = { sp = c.teal, undercurl = true },
    -- Messages and Modes
    ErrorMsg = { fg = c.red },
    WarningMsg = { fg = c.yellow },
    ModeMsg = { fg = c.fg_dark, bold = true },
    MsgArea = { fg = c.fg_dark },
    MoreMsg = { fg = c.blue },
    Question = { fg = c.blue },
    -- LSP Specific
    LspReferenceText = { bg = c.fg_gutter },
    LspReferenceRead = { bg = c.fg_gutter },
    LspReferenceWrite = { bg = c.fg_gutter },
    LspSignatureActiveParameter = { bg = c.lsp_signature_active_param, bold = true },
    LspCodeLens = { fg = c.comment },
    LspInlayHint = { bg = c.lsp_inlay_hint, fg = c.dark3 },
    LspInfoBorder = { fg = c.border_highlight, bg = c.bg_dark },
    -- Miscellaneous
    Bold = { bold = true, fg = c.fg },
    Conceal = { fg = c.dark5 },
    Directory = { fg = c.blue },
    Error = { fg = c.red },
    Folded = { fg = c.blue, bg = c.fg_gutter },
    Italic = { italic = true, fg = c.fg },
    NonText = { fg = c.fg_gutter, nocombine = true },
    SpecialKey = { fg = c.dark3 },
    Substitute = { bg = c.red, fg = c.black },
    Title = { fg = c.blue, bold = true },
    Todo = { bg = c.yellow, fg = c.bg },
    Underlined = { underline = true },
    Whitespace = { fg = c.fg_gutter, nocombine = true },
  }
end

return M
