local M = {}

M.get = function(c)
  return {
    -- Comments
    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { fg = c.red },
    ["@comment.hint"] = { fg = c.teal },
    ["@comment.info"] = { fg = c.blue2 },
    ["@comment.note"] = { fg = c.teal },
    ["@comment.todo"] = { fg = c.blue },
    ["@comment.warning"] = { fg = c.yellow },
    -- Literals
    ["@boolean"] = { link = "Boolean" },
    ["@character"] = { link = "Character" },
    ["@character.printf"] = { link = "SpecialChar" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Number" },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { fg = c.yellow },
    ["@string.escape"] = { fg = c.magenta },
    ["@string.regexp"] = { fg = c.blue6 },
    -- Constants & Variables
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { link = "@keyword" },
    ["@variable.builtin.c"] = { link = "@function.method" },
    ["@variable.builtin.python"] = { fg = c.param, italic = true },
    ["@variable.member"] = { fg = c.teal },
    ["@variable.parameter"] = { fg = c.param },
    ["@variable.parameter.builtin"] = { fg = c.param },
    -- Functions
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { fg = c.blue, bold = true },
    ["@function.method.call"] = { link = "@function.method" },
    ["@constructor"] = { fg = c.magenta, nocombine = true },
    ["@constructor.tsx"] = { fg = c.blue1 },
    -- Keywords
    ["@keyword"] = { fg = c.purple },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.coroutine"] = { link = "@keyword" },
    ["@keyword.debug"] = { link = "Debug" },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { fg = c.magenta },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { link = "@operator" },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "@keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    -- Types
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Special" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "@keyword" },
    -- Modules & Namespaces
    ["@module"] = { link = "Directory" },
    ["@module.cpp"] = { link = "PreProc" },
    ["@module.builtin"] = { fg = c.red },
    ["@namespace.builtin"] = { link = "@variable.builtin" },
    -- Operators & Punctuation
    ["@operator"] = { link = "Operator" },
    ["@punctuation.bracket"] = { fg = c.fg_dark },
    ["@punctuation.delimiter"] = { fg = c.blue5 },
    ["@punctuation.special"] = { fg = c.blue5 },
    ["@punctuation.special.markdown"] = { fg = c.orange },
    -- Properties & Attributes
    ["@property"] = { fg = c.teal },
    ["@annotation"] = { link = "PreProc" },
    ["@attribute"] = { link = "PreProc" },
    ["@label"] = { link = "Function" },
    -- Markup (Markdown/Doc)
    ["@markup"] = { link = "@none"},
    ["@markup.emphasis"] = { italic = true },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.teal },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.link.label.symbol"] = { link = "Identifier" },
    ["@markup.link.url"] = { link = "Underlined" },
    ["@markup.list"] = { fg = c.blue5 },
    ["@markup.list.checked"] = { fg = c.teal },
    ["@markup.list.markdown"] = { fg = c.orange, bold = true },
    ["@markup.list.unchecked"] = { fg = c.blue },
    ["@markup.math"] = { link = "Special" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.raw.markdown_inline"] = { bg = c.terminal_black, fg = c.blue },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
    -- Tags (HTML/XML/JSX)
    ["@tag"] = { link = "Label" },
    ["@tag.attribute"] = { link = "@property" },
    ["@tag.delimiter"] = { link = "Delimiter" },
    ["@tag.delimiter.tsx"] = { fg = c.delimiter_tsx },
    ["@tag.tsx"] = { fg = c.red },
    ["@tag.javascript"] = { fg = c.red },
    -- Diff
    ["@diff.delta"] = { link = "DiffChange" },
    ["@diff.minus"] = { link = "DiffDelete" },
    ["@diff.plus"] = { link = "DiffAdd" },
    -- Special
    ["@none"] = {},
  }
end

return M
