from util import Util

bg = "#222436"
bg_dark = "#1e2030"
bg_dark2 = "#2f334d"
bg_dark3 = "#444a73"
blue = "#7aa2f7"
blue0 = "#3e68d7"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
comment = "#636da6"
cyan = "#86e1fc"
dark5 = "#737aa2"
fg = "#c8d3f5"
fg_dark = "#828bb8"
fg_gutter = "#3b4261"
green = "#c3e88d"
green1 = "#41a6b5"
magenta = "#c099ff"
orange = "#ff966c"
purple = "#fca7ea"
red = "#ff757f"
red1 = "#c53b53"
teal = "#4fd6be"
terminal_black = "#444a73",
yellow = "#ffc777"
none = "NONE"

# dark = blend(c.bg_dark, 0.8, "#000000")      -- #181926
# bg_visual = blend(c.blue0, 0.35, c.bg)       -- #2b3b6e
# border_highlight = blend(c.blue1, 0.8, c.bg) -- #579dd6
# black = blend(c.bg, 0.8, "#000000")
# param = brighten(c.red, 0.05)
# g.terminal_color_8  = brighten(c.black)
# g.terminal_color_9  = brighten(c.red)
# g.terminal_color_10 = brighten(c.green)
# g.terminal_color_11 = brighten(c.yellow)
# g.terminal_color_12 = brighten(c.blue)
# g.terminal_color_13 = brighten(c.magenta)
# g.terminal_color_14 = brighten(c.cyan)
# g.terminal_color_15 = brighten(c.fg_dark)

dark = Util.blend(bg_dark, 0.8, "#000000")
bg_visual = Util.blend(blue0, 0.35, bg)
border_highlight = Util.blend(blue1, 0.8, bg)
black = Util.blend(bg, 0.8, "#000000")
param = Util.brighten(red, 0.05)
br_black = Util.brighten(black)
br_red = Util.brighten(red)
br_green = Util.brighten(green)
br_yellow = Util.brighten(yellow)
br_blue = Util.brighten(blue)
br_magenta = Util.brighten(magenta)
br_cyan = Util.brighten(cyan)
br_white = Util.brighten(fg_dark)

print(f"{dark = }")
print(f"{bg_visual = }")
print(f"{border_highlight = }")
print(f"{black = }")
print(f"{param = }")
print(f"{br_black = }")
print(f"{br_red = }")
print(f"{br_green = }")
print(f"{br_yellow = }")
print(f"{br_blue = }")
print(f"{br_magenta = }")
print(f"{br_cyan = }")
print(f"{br_white = }")
