local api = vim.api
local blend_bg = require("themes.util").blend_bg
local blend_fg = require("themes.util").blend_fg
local M = {}

M.get = function(c, t)
  local s = {
    Comment                     = { fg = c.comment, italic = true },
    ColorColumn                 = { bg = c.black },
    Conceal                     = { fg = c.dark5 },
    Cursor                      = { fg = c.bg, bg = c.fg },
    lCursor                     = { fg = c.bg, bg = c.fg },
    CursorIM                    = { fg = c.bg, bg = c.fg },
    CursorLine                  = { bg = c.bg_dark2 },
    CursorColumn                = { link = "CursorLine" },
    Directory                   = { fg = c.blue },
    DiffAdd                     = { bg = blend_bg(c.green1, 0.15, c.bg) },
    DiffChange                  = { bg = blend_bg(c.blue7, 0.15, c.bg) },
    DiffDelete                  = { bg = blend_bg(c.red1, 0.15, c.bg) },
    DiffText                    = { bg = c.blue7 },
    EndOfBuffer                 = { fg = c.bg },
    ErrorMsg                    = { fg = c.red },
    WinSeparator                = { fg = c.border_highlight, bold = true },
    Folded                      = { fg = c.blue, bg = c.fg_gutter },
    FoldColumn                  = { bg = t and c.none or c.bg, fg = c.comment },
    SignColumn                  = { bg = t and c.none or c.bg, fg = c.fg_gutter },
    SignColumnSB                = { bg = c.bg_dark, fg = c.fg_gutter },
    Substitute                  = { bg = c.red, fg = c.black },
    LineNr                      = { fg = c.fg_gutter },
    CursorLineNr                = { fg = c.orange, bold = true },
    LineNrAbove                 = { fg = c.fg_gutter },
    LineNrBelow                 = { fg = c.fg_gutter },
    MatchParen                  = { fg = c.orange, bold = true },
    ModeMsg                     = { fg = c.fg_dark, bold = true },
    MsgArea                     = { fg = c.fg_dark },
    MoreMsg                     = { fg = c.blue },
    NonText                     = { fg = c.dark3 },
    Normal                      = { fg = c.fg, bg = t and c.none or c.bg },
    NormalNC                    = { fg = c.fg, bg = t and c.none or c.bg },
    NormalSB                    = { fg = c.fg_dark, bg = c.bg_dark },
    NormalFloat                 = { fg = c.fg, bg = c.bg_dark },
    FloatBorder                 = { fg = c.border_highlight, bg = c.bg_dark },
    FloatTitle                  = { link = "FloatBorder" },
    Pmenu                       = { bg = c.bg_dark, fg = c.fg },
    PmenuMatch                  = { bg = c.bg_dark, fg = c.blue1 },
    PmenuSel                    = { bg = blend_bg(c.fg_gutter, 0.8, c.bg) },
    PmenuMatchSel               = { bg = blend_bg(c.fg_gutter, 0.8), fg = c.blue1 },
    PmenuSbar                   = { bg = blend_fg(c.bg_dark, 0.95, c.fg) },
    PmenuThumb                  = { bg = c.fg_gutter },
    Question                    = { fg = c.blue },
    QuickFixLine                = { bg = c.bg_visual, bold = true },
    Search                      = { bg = c.blue0, fg = c.fg },
    IncSearch                   = { bg = c.orange, fg = c.black },
    CurSearch                   = { link = "IncSearch" },
    SpecialKey                  = { fg = c.dark3 },
    SpellBad                    = { sp = c.red, undercurl = true },
    SpellCap                    = { sp = c.yellow, undercurl = true },
    SpellLocal                  = { sp = c.blue2, undercurl = true },
    SpellRare                   = { sp = c.teal, undercurl = true },
    StatusLine                  = { fg = c.fg_dark, bg = c.dark },
    StatusLineNC                = { fg = c.fg_gutter, bg = c.dark },
    TabLine                     = { bg = c.dark, fg = c.fg_gutter },
    TabLineFill                 = { bg = c.black },
    TabLineSel                  = { fg = c.black, bg = c.blue },
    Title                       = { fg = c.blue, bold = true },
    Visual                      = { bg = c.bg_visual },
    VisualNOS                   = { bg = c.bg_visual },
    WarningMsg                  = { fg = c.yellow },
    Whitespace                  = { fg = c.fg_gutter },
    WildMenu                    = { bg = c.bg_visual },
    WinBar                      = { link = "StatusLine" },
    WinBarNC                    = { link = "StatusLineNC" },
    Bold                        = { bold = true, fg = c.fg },
    Character                   = { fg = c.green },
    Constant                    = { fg = c.orange },
    Debug                       = { fg = c.orange },
    Delimiter                   = { link = "Special" },
    Error                       = { fg = c.red },
    Function                    = { fg = c.blue },
    Identifier                  = { fg = c.magenta },
    Italic                      = { italic = true, fg = c.fg },
    Keyword                     = { fg = c.cyan },
    Operator                    = { fg = c.blue5 },
    PreProc                     = { fg = c.cyan },
    Special                     = { fg = c.blue1 },
    Statement                   = { fg = c.magenta },
    String                      = { fg = c.green },
    Todo                        = { bg = c.yellow, fg = c.bg },
    Type                        = { fg = c.blue1 },
    Underlined                  = { underline = true },
    LspReferenceText            = { bg = c.fg_gutter },
    LspReferenceRead            = { bg = c.fg_gutter },
    LspReferenceWrite           = { bg = c.fg_gutter },
    LspSignatureActiveParameter = { bg = blend_bg(c.bg_visual, 0.4, c.bg), bold = true },
    LspCodeLens                 = { fg = c.comment },
    LspInlayHint                = { bg = blend_bg(c.blue7, 0.1, c.bg), fg = c.dark3 },
    LspInfoBorder               = { fg = c.border_highlight, bg = c.bg_dark },
    DiagnosticError             = { fg = c.red },
    DiagnosticWarn              = { fg = c.yellow },
    DiagnosticInfo              = { fg = c.blue2 },
    DiagnosticHint              = { fg = c.teal },
    DiagnosticUnnecessary       = { fg = c.bg_dark3 },
    DiagnosticVirtualTextError  = { bg = blend_bg(c.red, 0.1, c.bg), fg = c.red },
    DiagnosticVirtualTextWarn   = { bg = blend_bg(c.yellow, 0.1, c.bg), fg = c.yellow },
    DiagnosticVirtualTextInfo   = { bg = blend_bg(c.blue2, 0.1, c.bg), fg = c.blue2 },
    DiagnosticVirtualTextHint   = { bg = blend_bg(c.teal, 0.1, c.bg), fg = c.teal },
    DiagnosticUnderlineError    = { undercurl = true, sp = c.red },
    DiagnosticUnderlineWarn     = { undercurl = true, sp = c.yellow },
    DiagnosticUnderlineInfo     = { undercurl = true, sp = c.blue2 },
    DiagnosticUnderlineHint     = { undercurl = true, sp = c.teal },
  }

  local hl = api.nvim_set_hl
  for key, val in pairs(s) do hl(0, key, val) end
end

return M
