local M = {}

function M.get(c, o)
  local transparency = o.transparency
  local transp = transparency and c.none
  local s_transp = transparency and c.surface1
  local f_transp = (o.float.transparent and vim.o.winblend == 0) and c.none
  local p_transp = (transparency and vim.o.pumblend == 0) and c.none

  return {
    ColorColumn           = { bg = c.surface0 },
    Conceal               = { fg = c.overlay1 },
    Cursor                = { fg = c.base, bg = c.rosewater },
    lCursor               = { link = "Cursor" },
    CursorIM              = { link = "Cursor" },
    CursorColumn          = { bg = c.mantle },
    CursorLine            = { bg = c.bg_line },
    Directory             = { fg = c.blue },
    EndOfBuffer           = { fg = c.base, },
    ErrorMsg              = { fg = c.red, bold = true, italic = true },
    VertSplit             = { fg = s_transp or c.crust },
    Folded                = { fg = c.blue, bg = transp or c.surface1 },
    FoldColumn            = { fg = c.overlay0 },
    SignColumn            = { fg = c.surface1 },
    SignColumnSB          = { bg = c.crust, fg = c.surface1 },
    Substitute            = { bg = c.surface1, fg = c.pink },
    LineNr                = { fg = c.surface1 },
    CursorLineNr          = { fg = c.lavender },
    MatchParen            = { fg = c.peach, bg = c.surface1, bold = true },
    ModeMsg               = { fg = c.text, bold = true },
    MsgSeparator          = {},
    MoreMsg               = { fg = c.blue },
    NonText               = { fg = c.overlay0 },
    Normal                = { fg = c.text, bg = transp or c.base },
    NormalNC              = { fg = c.text, bg = transp or c.dim, },
    NormalSB              = { fg = c.text, bg = c.crust },
    NormalFloat           = { fg = c.text, bg = f_transp or c.mantle },
    FloatBorder           = { fg = c.surface1, bg = c.mantle },
    FloatTitle            = o.float.solid and { fg = c.crust, bg = c.lavender, }
      or { fg = c.subtext0, bg = f_transp or c.mantle },
    FloatShadow           = { fg = f_transp or c.overlay0 },
    Pmenu                 = { bg = p_transp or c.mantle, fg = c.overlay2, },
    PmenuSel              = { bg = c.surface0, bold = true },
    PmenuSbar             = { bg = c.surface0 },
    PmenuThumb            = { bg = c.overlay0 },
    PmenuExtra            = { fg = c.overlay0 },
    PmenuExtraSel         = { fg = c.overlay0, bold = true },
    Question              = { fg = c.blue },
    QuickFixLine          = { bg = c.surface1, bold = true },
    Search                = { bg = c.bg_search, fg = c.text },
    IncSearch             = { bg = c.bg_incsearch, fg = c.mantle },
    CurSearch             = { bg = c.red, fg = c.mantle },
    SpecialKey            = { link = "NonText" },
    SpellBad              = { sp = c.red, undercurl = true },
    SpellCap              = { sp = c.yellow, undercurl = true },
    SpellLocal            = { sp = c.blue, undercurl = true },
    SpellRare             = { sp = c.green, undercurl = true },
    StatusLine            = { fg = c.text, bg = transp or c.mantle },
    StatusLineNC          = { fg = c.surface1, bg = transp or c.mantle },

    StatusLineNormal      = { bg = c.blue, fg = c.crust, bold = true },
    StatusLineInsert      = { bg = c.green, fg = c.crust, bold = true },
    StatusLineVisual      = { bg = c.mauve, fg = c.crust, bold = true },
    StatusLineCommand     = { bg = c.yellow, fg = c.crust, bold = true },
    StatusLineReplace     = { bg = c.maroon, fg = c.crust, bold = true },
    StatusLineTerminal    = { bg = c.green, fg = c.crust, bold = true },
    StatusLineGit         = { fg = c.peach },
    StatusLineModified    = { fg = c.yellow },
    StatusLineFile        = { fg = c.text },
    StatusLineDiagError   = { link = "DiagnosticError" },
    StatusLineDiagWarning = { link = "DiagnosticWarn" },
    StatusLineDiagHint    = { link = "DiagnosticHint" },
    StatusLineDiagInfo    = { link = "DiagnosticInfo" },
    StatusLineLsp         = { fg = c.green },
    StatusLineLabel       = { fg = c.surface1 },
    StatusLineValue       = { fg = c.peach },
    StatusLineSeparator   = { fg = c.surface0 },

    TabLine               = { bg = c.crust, fg = c.overlay0 },
    TabLineFill           = { bg = transp or c.mantle },
    TabLineSel            = { link = "Normal" },
    TermCursor            = { fg = c.base, bg = c.rosewater },
    TermCursorNC          = { fg = c.base, bg = c.overlay2 },
    Title                 = { fg = c.blue, bold = true },
    Visual                = { bg = c.surface1, bold = true },
    VisualNOS             = { link = "Visual" },
    WarningMsg            = { fg = c.yellow },
    Whitespace            = { fg = c.surface1 },
    WildMenu              = { bg = c.overlay0 },
    WinBar                = { fg = c.rosewater },
    WinBarNC              = { link = "WinBar" },
    WinSeparator          = { fg = s_transp or c.crust },
  }
end

return M
